version: "2"
services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: vulcantv
            POSTGRES_DB: vulcantv
            POSTGRES_PASSWORD: password
        ports:
            - 5432:5432

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

    frontend:
        image: govulcantv_frontend_dev
        build:
            context: ./frontend/
            dockerfile: dev.Dockerfile
        ports:
            - 3000:3000
        volumes:
            - ./frontend:/usr/src/govulcantv/frontend
